### ISSUE TITLE
Issue at "python setup.py build"

### ISSUE THREAD

**Issue by EdgeSync** [skftn/upc_keys.py#3]
When running the command, got this error:
# 

upc_keys.c:21:25: fatal error: openssl/md5.h: No such file or directory
 #include <openssl/md5.h>
                         ^
compilation terminated.
# error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Fix:

Ensure you have libssl-dev installed. 

sudo apt-get install libssl-dev. 

Confirmed that this fixed it in Kali 2.0, and Mint 17.3 (for me anyway).
Might help anyone else stuck with this issue. Awesome work to Dev btw :D

**Comment by sanderfoobar** [comment]
I've added it to the readme, thanks dude :-)
