### ISSUE TITLE
Key not found

### ISSUE THREAD

**Issue by ShlomoRosenheimer** [skftn/upc_keys.py#8]
Somehow your script did not find my UPC key, although presenting 21 possible keys...
This service however found my key https://upc.michalspacek.cz/
I guess you are all using the same lib. How come your script did not manage to recover the key?
Also it was necessary to run the script like this:
sudo crack-upc -i wlan0 -s ...

**Comment by spaze** [comment]
I use modified `upc_keys.c` for https://upc.michalspacek.cz/ with support for more serial number prefixes. The original `upc_keys.c` uses just `SAAP`, I support `SAAP`, `SAPP`, `SBAP`. I guess your device has one of the two extra prefixes.

**Comment by ShlomoRosenheimer** [comment]
Thank you Michal for the excellent service.

**Comment by spaze** [comment]
If anyone cares, I've now published the modified sources here https://github.com/spaze/upc_keys-lambda

**Comment by sanderfoobar** [comment]
Ill modify readme.md to point to your repository - I don't have time to update this project.
